# **LABELING DATA AVETA**

Library

In [ ]:
! pip install transformers torch pandas openpyxl

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.3)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.9.0+cpu)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.11.12)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from transformers import pipeline

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

In [ ]:
# Membaca Data
# Pastikan kolom yang akan dilabeli bernama 'tokening' (hasil preprocessing)
data = pd.read_csv("data_aveta.csv")  # ubah sesuai nama file kamu
data = data.loc[:, ~data.columns.str.contains("^Unnamed")]
print(f"Total data: {len(data)}")
data.head()

Total data: 2449

  rating                                             ulasan labeling manual
0    5/5  Hotel yang sgt strategis di jalan malioboro. K...         Positif
1    5/5  Lokasi yang top. Di sekitar lokasi hotel banya...         Positif
2    2/5  Kurang saya rekomendasikan. Pesan premier room...         Negatif
3    5/5  nginap 2 hari dan 2 malam bersama istri dan an...         Positif
4    2/5  Saya memberikan bintang 2 ini sebelum saya mas...         Negatif

**Transformer Lbeling**

In [ ]:
#Inisialisasi Model Transformer
sentiment_analyzer = pipeline(
    "sentiment-analysis",
    model="w11wo/indonesian-roberta-base-sentiment-classifier",
    truncation=True,
    max_length=512
)

Device set to use cpu

In [ ]:
# Jalankan analisis untuk setiap teks
def get_label_result(text):
    if pd.isna(text):
        return np.nan
    try:
        result = sentiment_analyzer(
            text,
            truncation=True,
            max_length=512
        )[0]
        label = result["label"].upper()
        if label == "POSITIVE":
            return 1
        elif label == "NEGATIVE":
            return 0
        else:
            return np.nan
    except Exception as e:
        return np.nan
# Terapkan ke kolom 'Ulasan'
data['label'] = data['ulasan'].apply(get_label_result)

In [ ]:
# Hitung distribusi hasil labeling
hasil_label = data['label'].value_counts(dropna=False)
print("Statistik Labeling")
print(f"Total data       : {len(data)}")
print(f"Positif (1)      : {hasil_label.get(1, 0)}")
print(f"Negatif (0)      : {hasil_label.get(0, 0)}")
print(f"Belum terlabeli  : {hasil_label.get(np.nan, 0)}")
print("\n Persentase")
print((hasil_label / len(data) * 100).round(2))

Statistik Labeling
Total data       : 2449
Positif (1)      : 2242
Negatif (0)      : 188
Belum terlabeli  : 19

 Persentase
label
1.0    91.55
0.0     7.68
NaN     0.78
Name: count, dtype: float64

In [ ]:
def label(label):
    if label == 1:
        return "Positif"
    elif label == 0:
        return "Negatif"
    else:
        return None
data["label"] = data["label"].apply(label)

In [ ]:
data

,rating,ulasan,labeling manual,label
0,5/5,Hotel yang sgt strategis di jalan malioboro. K...,Positif,Negatif
1,5/5,Lokasi yang top. Di sekitar lokasi hotel banya...,Positif,Positif
2,2/5,Kurang saya rekomendasikan. Pesan premier room...,Negatif,Negatif
3,5/5,nginap 2 hari dan 2 malam bersama istri dan an...,Positif,Positif
4,2/5,Saya memberikan bintang 2 ini sebelum saya mas...,Negatif,Negatif
...,...,...,...,...
2444,5/5,Semoga beruntung 👍🏻,Negatif,Positif
2445,4/5,Playanan 👍👍👍,Positif,Positif
2446,1/5,Manyalah..,Negatif,Negatif
2447,5/5,Daerah Malioboro,Positif,Positif
2448,3/5,Manyanlah,Positif,Positif

**Negatif**

In [ ]:
df_negatif = data[data['label'] == "Negatif"]
print(df_negatif)

     rating                                             ulasan  \
0       5/5  Hotel yang sgt strategis di jalan malioboro. K...
2       2/5  Kurang saya rekomendasikan. Pesan premier room...
4       2/5  Saya memberikan bintang 2 ini sebelum saya mas...
6       1/5  Pengalaman menginap yang kurang menyenangkan  ...
22      1/5  Mati listrik sampai 20 menit, tidak ada penjel...
...     ...                                                ...
2400    3/5  Hotel yang terletak di jantung Malioboro ini m...
2430    5/5                    tidak bakalan balik lagiiiiii..
2435    5/5                   Pengalaman yang luar biasa jelek
2439    4/5                                Nongkring ajalah...
2446    1/5                                         Manyalah..

     labeling manual    label
0            Positif  Negatif
2            Negatif  Negatif
4            Negatif  Negatif
6            Negatif  Negatif
22           Negatif  Negatif
...              ...      ...
2400         Negatif  Negatif
2430         Negatif  Negatif
2435         Negatif  Negatif
2439         Negatif  Negatif
2446         Negatif  Negatif

[188 rows x 4 columns]

In [ ]:
for idx, ulasan in df_negatif['ulasan'].items():
    print(f"{idx}: {ulasan}")
    print('-' * 50)#negatif

0: Hotel yang sgt strategis di jalan malioboro. Karyawan ramah2. Kamar bersih. House keeping jg baik, bersih dan cepat kerjanya.Minusnya: 1. Tidak ada lahan parkir. Sangat terbatas harus valet semua ninggal kunci. Bikin tdk nyaman.2. Kamar mandi tdk ada hand shower kalau bawa baby akan kesusahan utk mandi krn hanya shower yg ada di atap saja 3. Untuk breakfastnya variasinya lumayan hanya saja rasanya sangat kurang. Mnrt sy tdk enak. Hehehe. Harusnya bisa lbh enak lg. Semoga ditingkatkan 4. Kamar tidak kedap. Terutama kalau tarik kursi sangat jelas dr kamar sebelah Semoga ada perbaikan yah. Hotel ini sangat rekomended untuk dicoba. Semoga pelayanan dan kebersihannya dijaga sama bahkan lbh baik lg.
--------------------------------------------------
2: Kurang saya rekomendasikan. Pesan premier room di link nya aveta hotel, gak dapet bf. Padahal waktu check inn, dikabari kita free bf. Setelah esok hari mo bf, nomor kamar kita gak ada dlm list bf alias exclude bf!
Kamar cukup bersih dan semua berfungsi dgn baik, hanya beberapa kali listrik padam. Sudah konfirm, nyala lg (sekelas hotel bisa mati lampu juga)
Amenities yg ada dikamar kami ada salah 1 nya sudah dlm keadaan setengah terbuka. Langsung buang!
Yang katanya menghadap malioboro bener, tapi terhalang pohon dan tembok. Soo percuma ae seh.
Makan minum gak icip². Jadi no komen.
--------------------------------------------------
4: Saya memberikan bintang 2 ini sebelum saya masuk kamar. Karena kamar akan siap nanti di jam 3. Hari ini tgl 13-April 25 dan saya menulis di jam 12:39.Kekecewaan saya adalah dimulai dari sebelum melakukan booking. Saya coba berkomunikasi melalui WA. Dari bahasa WA pun sepertinya sudah agak defensif ketika saya mempertanyakan masalah early check in.Early check in bisa dilakukan paling cepat jam 12 dan itupun tergantung kesiapan kamar. Ok, saya terima alasan ini. Dan ketika saya sampai, ternyata pernyataan berubah menjadi jam 3 sore. Kemudian FD menyampaikan, ada yg check out jam 12, pengerjaan paling 1 jam. Jadi saya bilang, sudah bisa masuk dong jam 1 siang. Dan langsung dijawab kemungkinan di jam 3 siapnya karena banyak kamar yg check out… (speechless…)Dan WA pun sampai sekarang belum direspon..Terima kasih Aveta sudah memberikan pelajaran
--------------------------------------------------
6: Pengalaman menginap yang kurang menyenangkan  .. 😔Kami Menginap di tanggal  5-7 Mei  2025 shower toilet  rusak info ke Room service  slow respon  hari berikutnya baru di perbaiki..Di hari kedua mati lampu selama 30 menit tanpa ada penjelasan apapun..Mohon di perbaiki  untuk kedepannya
--------------------------------------------------
22: Mati listrik sampai 20 menit, tidak ada penjelasan apapun dari pihak hotel, pelayanan tidak memuaskan.
--------------------------------------------------
44: Rencana bulan depan mau menginap disini, ini parkir mobilnya gmn atau sebelah mana ya?
--------------------------------------------------
46: Peraturan Hotel payah, pesan ada balkoni supaya bisa smoking ternyata tetap no smoking. Baru kali ini ketemu hotel outdoor balkoni nya no smoking.
--------------------------------------------------
57: Saya merasa dipermainkan oleh pihak hotel layanannya tidak profesional, awalnya kami akan liburan di jogja lalu kami pesan hotel selama 2 hr tg 27-29 Nov 24 lewat traveloka kami memilih hotel yg aksesnya mudah kemana-mana setelah sampai di hotel kira2 pk 15.00 pihak receiption mengatakan kalo voucher hotel blm terbit kami disuruh menunggu padahl kami juga sudah memegang bukti/issued  tetap hrs menunggu pihak hotel menerima voucher dri traveloka, sebelumnya kami tidak pernah bermasalah menggunakan traveloka, liburan ke luar negeri pun menggunakan traveloka aman2 saja, akhirnya saya telpon pihak traveloka kalo saya blm bisa masuk kamar krn voucher blm terbentuk, akhirnya kami masih disuruh menunggu sampe pk 19.00 akhirnya kami bisa masuk kamar tapi pihak hotel meminta kami utk membayar karena kami telah melakukan cancled melalui traveloka pdhl tdk ada pemberitahuan sama sekali dari pihak traveloka atas pembatalan tersebut, sampe kamar kami membuka email dan ternyata pk 16.00 voucher hotel sudah terbentuk lalu kami konfirm lagi ke pihak traveloka bhw kami disuruh bayar cash akhirnya pihak traveloka mengirim email dan juga telpon kami hingga pk 23.00 bahwa semuanya sudah clear, besok paginya kami breakfast dan tidak ada pemberitahuan apa2, kami menitipkan koper krn harus downgrade room kami ikuti, akhirnya kami melakukan perjalanan dulu utk ziarah ke sendangsono, sesampainya di hotel pk 19.00 kami diinfo oleh petugas hotel yg sudah ganti bahwa kami tidak bisa menginap sebelum membayar yg kemarin malam…..Kami memutuskan utk pindah hotel dan membayar yg satu malam kemarin, ternyata tidak profesional sekali layanannya dan KAMI SANGAT KECEWA HANYA BERMALAM 2 HR KAMI DIPERSULIT, KAMI TIDAK AKAN PERNAH DATANG LAGI KE HOTEL AVETA DAN TIDAK AKAN MEREKOMENDASIKAN KE SIAPAPUN ATAS HOTEL INI
--------------------------------------------------
62: dapat kamar yg konekting suara orang kamar sebelah ngak ada kedap sama sekali...
terdengar jelas seperti kita berada dalam satu kamar.....
terdengar keras banget orang sebelah lagi wikwik...
--------------------------------------------------
72: Saya baru-baru ini menginap di hotel ini, dan itu benar-benar mimpi buruk dari awal hingga akhir. Kamarnya kotor, dengan jamur di langit-langit kamar mandi, permukaan yang berdebu, dan wewangian buatan yang sangat kuat yang jelas-jelas menutupi kurangnya pembersihan yang tepat. Ketika saya mengeluh, manajer meja depan sangat tidak profesional dan meremehkan, bahkan mengejek kekhawatiran saya.Mereka menunjukkan kepada kami kamar alternatif dengan dinding kuning dan kotor dan berjanji untuk mengecatnya ulang. Hasilnya? Kamar yang berbau asap cat baru, yang mereka harapkan akan kami terima. Kondisinya tidak hanya tidak menyenangkan tetapi juga sangat tidak sehat, dan sikap manajer meja depan memperburuk semuanya.Karena keluhan saya diabaikan, saya menghubungi Booking com untuk meminta bantuan, dan meskipun mereka berhasil menyelesaikan kompensasi, manajemen hotel membalas dengan menuntut kami check out pukul 11 ​​malam - sesuatu yang belum pernah saya alami sebelumnya! Akhirnya, kami tinggal sampai dini hari, hanya untuk melarikan diri dari tempat yang mengerikan ini.
--------------------------------------------------
103: Semua perfect, kecuali kita masih disuruh nunggu walaupun check in jam 4 sore.
--------------------------------------------------
107: Parkir valey lemot,ambil mobil d suruh nunggu 1,5 lebih payah...
--------------------------------------------------
110: Point + tempat di malioboro sebelahan sama plaza malioboro, banyak pedagang makanan enak2 di depannya. Kamarnya luas tapi di bawah meja terlihat kotor seperti bekas tetesan kopi yg tidak bisa hilang jadi tidak enak dipandang. Bantal ada noda kuning. Saya booking kamar yang ada balcony nya. Meja berdebu tempat kopi dan teh berdebu bahkan gula sudah terlihat lama tidak di ganti.
--------------------------------------------------
118: Bukan nginep di sini cuma numpang istirahat aja
--------------------------------------------------
136: Untuk ke 3 kalinya saya nginap di sini tempat yg strategis dekat malioboro..hari pertama menu nasi goreng dan bihun goreng biasa saja tidak ada rasa..hambar dan hari ke 2 nasi gorengnya hambar tidak ada rasa begitu jg dengan mie goreng
--------------------------------------------------
137: PARKIRANNYA NGGAK AMAN. NARO BARANG DI DASBOR ILANG... Hadehhh
--------------------------------------------------
141: Sebenernya udah 2x nginep di sini,kali ini pakek acara deposit kamar,nah pas checkout gak d ksh tau klo bawa smua kunci,kunci sy tinggal d kamar karena biasanya d hotel lain tdk masalah,karena jg harus check,apalagi lobby d lantai 8 yg bikin agak merepotkan yah menurut saya,untuk makanan lumayan lah ya untuk rasa,tapi untik parkir sempit dan ditutup jam 5 sore jalan dpn hotel alhasil nunggu jam 9 mlm dl baru bs parkir
--------------------------------------------------
154: 25-26 april 2024 Kami sewa family triple room, yg isinya 3 bed tapi cuma terdapat 2 mug, 2 coffee, 2 sugar, n sampo habis Kami sewa extra bed di superior room, tp cuma dpt 2 tiket breakfast Makanan ok
--------------------------------------------------
162: sorry harus kasih 2 star. Saya family traveller with kids dan lansia. Kyk nya utk yg bawa anak harus agak pikir2 dulu kl mau stay. Mau kasih 1 star sbnrnya tapi krn g tega jadinya 2 star.(+) lokasi di malioboro pusat jogja(+) air panas dan ac okelah(-) kamar banyak semut. Dari semua hotel yang seumur hidup didatangin, baru kali ini nemu yg semutnya banyak. Semut di meja kamar, luggage ruck, dan wastafel. Kalau cuma 1-2 ekor ya udahlah, tapi ini tuh banyak banget. Sudah coba bunuhin semutnya sendiri tapi tetap dateng terus. Entah pest control disini itu gmn. Roti yang dibeli dari luar kota sampai ud disemutin semua dan kami rugi hampir 50rb lebih. Udh bilang ke tim hotel utk dibersihin kamarnya dan JANGAN PAKAI BAYGON, tapi nyatanya ya tetap byk semut dan sepertinya tetap pakai baygon meski baunya disamarkan dgn pewangi. Al hasil minta ganti kamar, tapi ya masih ada semut tapi at least sdkt lebih baik.(-) resepsionis di lantai 8(-) tidak ada jet shower di wc, hanya sistem bidet saja : Ac yg netes di lantai 1 juga tetap netes dari hari pertama cek in.Saya rasa ujung”nya komen ini cuma dibalas dgn automatic message dari tim hotel, jadi ya sudah semoga semua bisa lebih baik lagi nantinya dan pembeli diharap bisa lebih kritis juga dalam memilih hotel utk diinapi terutama kalau ada anak2.
--------------------------------------------------
164: Menginap di kamar deluxe untuk 1 hari dengan balkon, kamar cukup bagus dan ac sangat dingin, lantainya sangat bantu kamarnya jd terasa lebih dingin lagi.  Lalu karena ada bbrp hal akhirnya pesan satu kamar superior dgn twin bed, luas kamarnya jauh lebih besar karna tanpa balkon. Namun saat masuk kamarnya, lantainya sangat lengket (entah apa yang salah sama surface liquid nya, pokonya ga enak banget dikaki), kami yg suka barefoot di dlm ruangan cukup terganggu dgn itu. Interior ruangan dan kamar mandi di kamar superior lebih bagus, bersih dan luas dibanding kamar deluxe (banyak noda kerak air). Ada pintu connecting room, ruang kamar kurang kedap suara. Resepsionis kurang informatif dan bicara terlalu cepat, jd beberapa kali harus mengulang.Oya saat checkout kami meminta bantuan trolley hotel, barang diangkut duluan kebawah dan kami turun menyusul sekitar 15 menit kemudian. Agak kaget karena barang² sudah tergeletak di lantai kotor (seharusnya tetap di trolley gak sih sampai tamu benar² akan pergi? Cmiiw) dan barang ditinggal tanpa pengawasan security..Overall pengalaman menginap disini lumayan berkesan karna lokasinya yg strategis sangat mudah diakses. Semoga setiap masukan reviewer bisa ditampung pihak hotel dan menjadi pertimbangan untuk jd lebih baik lagi pelayanannya. Terimakasih
--------------------------------------------------
169: Sudah ketiga kalinya menjenguk putri ku, yg kebetulan (Nb ; bekerja disekitar situ) kalo liat hotelnya dari luar sih lumayan bagus......cuma, kita kan ga masuk apalagi check inn
--------------------------------------------------
173: Jam Check In jam 15:00 - Jam Check Out jam 12:00. Mau stay  lebih dari satu malam tidak jadi dan kami pindah hotel. Stay di lantai 5 tapi mulai dari jam 10:00 pagi house keeping sudah mulai bersih bersih di kamar lain sekitar kamar tempat kami menginap, bising kursi meja digeser geser, padahal jika kami mengeser tempat tidur atau merokok didalam ruangan akan didenda 700.000 tetapi yang mereka lakukan sangat mengganggu dan itu pada ahirnya menjadi tidak sebanding dengan harga yang kami bayar. Tentang lokasi: sangat menarik karena keluar pintu hotel langsung atmosphere Malioboro kental terasa.
--------------------------------------------------
202: Hotel dengan regulasi paling aneh.1. Punya fasilitas balkon tapi tidak boleh merokok di balkon..??????2. Fasilitas balkon punya pintu, tapi kunci pintu tidak boleh di tinggal (kamar executive) jadi jika ingin buka balkon harus telp petugas.. Kalau mau dikunci.. Harus telp lagi atau tidak usah di kunci...???Tolong manajemen membuat kebijakan yang manusiawi.. Baru kali ini ketemu hotel seperti ini..
--------------------------------------------------
206: Kamarnya besar dan sangat bagus, pelayanannya sangat baik dan banyak pilihan untuk sarapan. Lokasi sangat bagus karena tepat di samping mall. Kekurangan dari hotel ini adalah kolam renangnya yang terkesan kotor dan tidak terawat
--------------------------------------------------
239: Satu nya keunggulan cuma lokasinya di jl. Malioboro. Sisanya nggak worth it.
--------------------------------------------------
240: Kamar hotel OK (bersih dengan selimut yang bau apek, rapi seolah olah semua telah dibersihlan, kasur enak dari pada tidur dilantai, AC dingin) Toiletnya Ok ( bersih dengan banyak bercak kotor dimana mana, modern) dengan sabun dan shampo yg baik, menu sarapan enak dan banyak pilihan, cuma pelayanan receptionist terlalu kaku, tidak ramah seperti robot, kalau bicara pakai masker baiknya pelan pelan karena kita tidak mengerti apa yg diucapkan sehingga tampak seperti kumur-kumur. Yg jelas pelananan nya dari semua pekerja sangat bad attitude. Rate harga terlalu tinggi, mungkin karena lagi weekend dan lagi liburan anak sekolah. Hotel ini layak diberikan penghargaan hotel dengan pelayanan terburuk ( bad service).
--------------------------------------------------
248: Saya ambil yg superior room 800rb semalam, dan extend 5 hari di kamar 505.Proses check in mendebarkan, krn saya sebut nama suami tidak ada di data CS, stlh bbrp saat ternyata ada, ok it fine.Kunci harus pakai deposit 200, sudah ✅. Saya menuju kamar utk menaruh koper. Sy balik lagi ke CS mnt kunci tambahan, diminta lagi 200 deposit. Sy tegasin dong kok bisa kan dapet satu, masa deposit lagi sih, tnyta CS berinisial R ini menganggap sy mnt kunci ketiga padahal kunci baru satu doang, tp aqirnya ga jadi deposit kedua, it oke.Sampai di kamar saya menghubungi CS, request jika membersihkan kamar, saya mau by phone saja.Lantas siang kedua saya pergi sebentar keluar, betapa terkejutnya kamar saya bersih sekali. Hebat bgt hotelnya tim house keeping bisa nyelonong masuk kamar orang seenaknya. Saya tidak pasang "makeup room" lho.Saya sudah ditemui oleh pihak FO manager dan diberi bbrp kompensasi.Bayangkan 5 hariiii extend, uang uda masuk ditarik juga ga bisa kan, lha kok siang kedua uda dapat kejutan spesial. Hotel aveta luar biasa tingkat kebersihannya bukan.Semoga pihak terkait dapat menemui jalan yg benar dan tidak tersesat lagi.
--------------------------------------------------
256: Pelayanan check in agak lama, meskipun kami sudah siap check in dari jam stengah 2, tapi kami baru bisa masuk kamar stelah tunggu stengah jam lebih. Kolam renang nyaman dan anak2 suka sekali, cuma karena bersebelahan dengan food lounge, kursi tendanya sering dipakai untuk merokok. Sampah makanan dan minuman, juga puntung rokoknya tidak segera dibersihkan, jadi terkesan kumuh. Untuk kamar tidak ada keluhan, bersih dan rapi. Oiyaa, showernya bocor, jadi kalo dipakai mandi muncrat kemana2 sampai keluar kamar mandi airnya
--------------------------------------------------
263: Kamar ok lumayan luas dan letak yg strategis sarapan untuk rasa kurang walau varian banyak dikasih pinjam setrika free, vale penuh pelayan
--------------------------------------------------
275: Letak  strategis, karyawan ramah semua dan sangat membantu.., menginap dua malam di kamar executive family lantai 2, sebenarnya kamarnya nyaman cuma sangat terganggu dengan suara mesin atau apa namanya gak tau yg berbunyi dan berdengung setiap saat siang malam, mungkin karena letak kamarnya paling ujung, tapi beneran ganggu banget  sampai tengah malam juga bunyi terus  apalagi kalau malam hari pasti terdengar lebih keras
--------------------------------------------------
277: Hotel yg berda tepat di jalan malioboro,, jd dari lokasi sangat strategis, kamar bagus, kebersihan juga ok.Hanya saja utk parkir mobil agak susah, parkiran kecil dan sempit.Dan kebetulan saya pesan kamar executive utk 2 malam,, di hari saya dtg ada free mini bar, di hari kedua tidak diberi.Dan handuk dihari pertama ada 2 handuk besar, ada 2 handuk muka,, tetapi di hari kedua tidak ada handuk muka.Rasa makanan di resto biasa saja.Tp overall masih ok.
--------------------------------------------------
281: Menang di lokasi aja  sma hotel baru, pelayanan standart kamar ada balkon tp dikunci, niat pilih nginap krn bisa liat malioboro, ni mlah ga bsa liat apa2 dr kamar. Hub receptionis ga ada solusi. Dibilang krn sharing jd ga dbuka, pdhal smpe besok kmr sblah ga ada yg isi,, heran kaku banget.Toilet utk cebok anak susah, kerannya ga ada cma lgsung pancoran, harga terlalu tggi, msh bnyak yg bntang 3 skitar situ yg lbh worth it.
--------------------------------------------------
305: Udah berkali2 tiap ke jogja nginepnya di hotel Aveta, tapiii....Aaahh, lg kecewa sama pelayanan parkir, pdhal untuk hotelnya udah bagus, strategis, ramah stafnya, makanannya pun enak2, tp buat liburan kali ini lg kecewa sama pelayanan parkirnya. Udah jelas2 kartu parkir ada plat nomornya, ditanya ini bnr asli apa ga tulisan nomor platnya, pdhal yg catat jg org hotel di kartu parkir. Udah gt yg diambil mobilnya bukan mobil kita, malah mobil org lain, kan udah nampak plat nomornya di kartu parkir 😅Nunggu sejaman, ampe anak ngereog saking lamanya, greget sumpah.Lain kali tlg komunikasi antar staf lebih ditingkatkan, agar tidak ada misscom kyk yg saya alami hari ini 🙏Terima kasih untuk liburan kali ini ya hotel aveta, walaupun sedikit kecewa saya akan tetap menginap di aveta tiap liburan ke Jogja.
--------------------------------------------------
312: semua sudah bagus keluarga kami paling tidak 2 bulan sekali menginap di Aveta
yang masih tetap kurang bagus makanan pagi
terutama mie Aceh aduh rasanya betul² tidak enak
--------------------------------------------------
318: Kamar sih luas tapi maaf berdebu dan kotor banget palagi di kolong meja n kursinya. Anak saya jadi bengek gegara main di lantai.
Air panasnya juga kurang hot.
Untuk pelayanan cukup memuaskan.
--------------------------------------------------
333: 1. Kamar cukup bersih2. Maintenance perlu lebih ditingkatkan, supaya kejadian floor drain mampet tidak terulang lagi.3. Staff house keeping harus lebih perduli dalam bekerja, mestinya setelah perbaikan drain yang mampet, bekas tapak sepatunya dibersihkan, keset yg basah juga diganti, tanpa harus diminta.4. Utk yang bawa mobil, petunjuk masuk ke hotel tidak jelas, mesti tanya ke orang, jalan masuk ke hotel juga paspasan, harus gantian kalau berpapasan, area parkir sangat minim, keluar masuk susah sewaktu padat kendaraan. Kendaraan harus di valet dan parkir ditempat lain kalau area parkir penuh. Petugas valet tidak jelas. Jadi terkait parkir mobil ini bener2 harus dibenahi dengan serius.
--------------------------------------------------
334: Menang di jalan raya malioboro nya sajaParkir kurang banget.Resepisonisnya di lantai 8, jadi dari parkiran naik dulu pakai lift, nanti turun lagi Cek in jam 3, banyak tamu yang tidak tau kalau cek in jam 3 sore, semua dinilang di prioritaskan. Tp tetap juga ga bisa cek in lebih awal dari jam 3.Resto kecil Kolam renang tidak terawat
--------------------------------------------------

Unlabeled

In [ ]:
df_unlabeled = data[data['label'].isna()]
print(df_unlabeled)

     rating                                             ulasan  \
90      4/5  Studio anak harusnya ada jadwal sore dan malam...
98      5/5  Saya booking 2 kamar untuk 4 malam, tapi saat ...
133     5/5  Rombongan Tamu pakai Hiace Premio Luxury 8 sea...
1136    1/5  maaf pak kmrn pak GM blg saya disuruh email da...
1258    3/5  Akses kendaraan masuk hotel, menjadi kendala k...
1426    3/5  Masih banyak perbaikan yang perlu di perbaiki,...
1499    5/5  Firdaus , isa , aulia , yuni terima kasih untu...
1553    5/5  Depan jalan malioboro, namun untuk skrng krna ...
1617    5/5                        Mimpi itu menjadi kenyataan
1646    3/5  Parkirnya perlu desain yg bagus fan dr depan t...
1773    5/5  Sdh membuka akses jalan kecil samping maliobor...
1780    5/5                      Great, selangkah ke malioboro
1860    1/5           hotel masih baru dan dipaksakan sdh buka
1935    5/5   Turun kamar hotel langsung Malioboro\nMuaantabbb
2066    4/5                                 Ok, sesuai harapan
2074    4/5                          Sesuai yg sy inginkan....
2118    2/5                             Tdk ada imformasi wifi
2201    5/5             Hanya satu langkah menyeberang ke Mall
2415    5/5  Masya Allah boleh aja ajak anak liburan biar m...

     labeling manual label
90           Negatif  None
98           Negatif  None
133          Negatif  None
1136         Negatif  None
1258         Positif  None
1426         Positif  None
1499         Positif  None
1553         Positif  None
1617         Positif  None
1646         Negatif  None
1773         Positif  None
1780         Positif  None
1860         Negatif  None
1935         Positif  None
2066         Positif  None
2074         Positif  None
2118         Negatif  None
2201         Positif  None
2415         Positif  None

In [ ]:
for idx, ulasan in df_unlabeled['ulasan'].items():
    print(f"{idx}: {ulasan}")
    print('-' * 50) #unlabeled

90: Studio anak harusnya ada jadwal sore dan malam dan anak usia 7 thn biasanya free tp ini bayar.
--------------------------------------------------
98: Saya booking 2 kamar untuk 4 malam, tapi saat mau check in disuruh nunggu jam 15:00 WIB, mohon penjelasan krn biasanya jam 14:00 sudah boleh CI
--------------------------------------------------
133: Rombongan Tamu pakai Hiace Premio Luxury 8 seat menginap di Aveta Hotel Malioboro
--------------------------------------------------
1136: maaf pak kmrn pak GM blg saya disuruh email dan beri no whatsapp sudah sy info dan sdh sy email tetapi sy tdk mendapatkan balasan smp dgn hari ini ya. dan utk booking, mmg tdk menggunakan nama sy. menggunakan nama “adi rachman” tgl 4-6 oct boleh silahkan d check. terimakasih.
--------------------------------------------------
1258: Akses kendaraan masuk hotel, menjadi kendala kelancaran manakala terjadi penutupan jalan Malioboro dari jam 18-21...
--------------------------------------------------
1426: Masih banyak perbaikan yang perlu di perbaiki, seperti pelayanan, tempat parkir, dan beberapa fasilitas hotel
--------------------------------------------------
1499: Firdaus , isa , aulia , yuni terima kasih untuk pelayanan nya
--------------------------------------------------
1553: Depan jalan malioboro, namun untuk skrng krna ad pembatasan roda empat agak sulit jika bawa kendaraan di jam tertentu
--------------------------------------------------
1617: Mimpi itu menjadi kenyataan
--------------------------------------------------
1646: Parkirnya perlu desain yg bagus fan dr depan tidak nampak
--------------------------------------------------
1773: Sdh membuka akses jalan kecil samping malioboro mall
--------------------------------------------------
1780: Great, selangkah ke malioboro
--------------------------------------------------
1860: hotel masih baru dan dipaksakan sdh buka
--------------------------------------------------
1935: Turun kamar hotel langsung Malioboro
Muaantabbb
--------------------------------------------------
2066: Ok, sesuai harapan
--------------------------------------------------
2074: Sesuai yg sy inginkan....
--------------------------------------------------
2118: Tdk ada imformasi wifi
--------------------------------------------------
2201: Hanya satu langkah menyeberang ke Mall
--------------------------------------------------
2415: Masya Allah boleh aja ajak anak liburan biar mereka bahagia
--------------------------------------------------

In [ ]:
# data = data.drop(columns=["label tranformer"])

In [ ]:
# # Simpan Hasil ke File
# data.to_csv("labeling_transformer_aveta.csv")